export const GET_SHOPS_REQUEST = 'GET_SHOPS_REQUEST';
export const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS';
export const GET_SHOPS_FAILURE = 'GET_SHOPS_FAILURE';

export const CREATE_SHOPS_REQUEST = 'CREATE_SHOPS_REQUEST';
export const CREATE_SHOPS_SUCCESS = 'CREATE_SHOPS_SUCCESS';
export const CREATE_SHOPS_FAILURE = 'CREATE_SHOPS_FAILURE';
