export const GET_RECENT_TOPICS_REQUEST = 'GET_RECENT_TOPICS_REQUEST';
export const GET_RECENT_TOPICS_SUCCESS = 'GET_RECENT_TOPICS_SUCCESS';
export const GET_RECENT_TOPICS_FAILURE = 'GET_RECENT_TOPICS_FAILURE';

export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';

export const GET_INTERESTED_TOPICS_REQUEST = 'GET_INTERESTED_TOPICS_REQUEST';
export const GET_INTERESTED_TOPICS_SUCCESS = 'GET_INTERESTED_TOPICS_SUCCESS';
export const GET_INTERESTED_TOPICS_FAILURE = 'GET_INTERESTED_TOPICS_FAILURE';

export const GET_MY_TOPICS_REQUEST = 'GET_MY_TOPICS_REQUEST';
export const GET_MY_TOPICS_SUCCESS = 'GET_MY_TOPICS_SUCCESS';
export const GET_MY_TOPICS_FAILURE = 'GET_MY_TOPICS_FAILURE';
