export const GET_CLINICS_REQUEST = 'GET_CLINICS_REQUEST';
export const GET_CLINICS_SUCCESS = 'GET_CLINICS_SUCCESS';
export const GET_CLINICS_FAILURE = 'GET_CLINICS_FAILURE';

export const GET_NEARBY_CLINICS_REQUEST = 'GET_NEARBY_CLINICS_REQUEST';
export const GET_NEARBY_CLINICS_SUCCESS = 'GET_NEARBY_CLINICS_SUCCESS';
export const GET_NEARBY_CLINICS_FAILURE = 'GET_NEARBY_CLINICS_FAILURE';

export const GET_POPULAR_CLINICS_REQUEST = 'GET_POPULAR_CLINICS_REQUEST';
export const GET_POPULAR_CLINICS_SUCCESS = 'GET_POPULAR_CLINICS_SUCCESS';
export const GET_POPULAR_CLINICS_FAILURE = 'GET_POPULAR_CLINICS_FAILURE';

